# Generated by Django 5.0.4 on 2024-04-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postdisplay', '0002_postview_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='postview',
            name='post_details',
            field=models.TextField(default=''),
        ),
    ]
