# Generated by Django 5.0.4 on 2024-04-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postdisplay', '0003_postview_post_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postview',
            name='post_user',
            field=models.CharField(default='', max_length=20),
        ),
    ]
